### ISSUE TITLE
clicking in Output Window hides it

### ISSUE THREAD

**Issue by Trass3r** [sirmspencer/vscode-autohide#19]
Clicking into the output window hides it.
Is it an issue with the extension or an individual setup problem?

**Comment by ZaLiTHkA** [comment]
I've just recently started learning about the VSCode extensions API myself, so I'm only speculating here... but I suspect this may quite simply come down to "intended behaviour" from the VSCode Extensions API... 🤔 

in the API docs, `onDidChangeTextEditorSelection` itself is described as:

> An [Event](https://code.visualstudio.com/api/references/vscode-api#Event) which fires when the selection in an editor has changed.

digging a bit deeper, [this comment](https://github.com/microsoft/vscode/issues/86871#issuecomment-574722564) in a different issue explains further by stating:

> This means it fires whenever that property changes, and that includes mouse double click, mouse click & drag and keyboard.

from this, I would assume that the "Output" panel is treated as an "editor" of sorts, triggering this same event, and thereby triggering the functionality from _this_ extension that is attached to it.

for anyone else who finds this one, I'd recommend just disabling the "Auto Hide Panel" option for this extension.

for anyone else who finds this one, I'd recommend just disabling the "Auto Hide Panel" option for this extension.

---

for anyone else who finds this one, I'd recommend just disabling the "Auto Hide Panel" option for this extension.

since auto-hiding panels is something I've wanted from my first encounter with VSCode, I'm going to dig into this extension code myself in the "Near Future" and see what I find. there might be a way to get a little more context regarding **where** the selection cursor has moved to, which could be checked [over here](https://github.com/sirmspencer/vscode-autohide/blob/e01e0c1ce400d0844d903781779c23e7e07672f7/src/extension.ts#L12)...

either way, at this point in time I need to get on with my normal day-job, which only involves _using_ VSCode, not _extending_ it..

**Comment by sirmspencer** [comment]
Yeah, so the issue is that the output panel is somehow an editor.  Ive been experiencing issues with this recently, so I will elevate this request.  Im hoping that that event exposes the editor name or some other property I can use to make an exception for the hide call. 

Im working two jobs right now.  Im not sure Ill be able to get to this until May.

**Comment by artginzburg** [comment]
Also have this problem.

The Output panel is indeed considered an editor for some reason (e.g. built-in wordPart / camel case navigation works inside it). My solution to this for now is not clicking into it, and using mouse wheel + keyboard to navigate or select.

**Comment by Trass3r** [comment]
Yeah I've been right-clicking+Esc to get the cursor there and then used the keyboard.

**Comment by spikespaz** [comment]
I'm bumping this because it's a pretty annoying problem that affects my work daily, only solution is to not use the auto hide panel feature, which is not actually a solution.
