### ISSUE TITLE
executes hiding on init before it reads config

### ISSUE THREAD

**Issue by mrx23dot** [sirmspencer/vscode-autohide#39]
Type: <b>Bug</b>

I setup addon  to only hide bottom panel
    "autoHide.autoHideSideBar": false,

I open a new folder
but side bar auto hides, it shouldn't 

When addon is disabled sidebar stays open, which is expected.

Same way when I enable addon, it auto hides side bar instantly, even though I specify not to in config
once I reopen sidebar it doesn't hide it again.

I think it executes hiding on init before it reads config.

Extension version: 1.0.8
VS Code version: Code 1.73.1 (6261075646f055b99068d3688932416f2346dd3b, 2022-11-09T04:27:29.066Z)
OS version: Windows_NT x64 10.0.19045
Modes: Unsupported
Sandboxed: No

<details>
<summary>System Info</summary>

|Item|Value|
|---|---|
|CPUs|Intel(R) Core(TM) i7-10510U CPU @ 1.80GHz (8 x 2304)|
|GPU Status|2d_canvas: enabled<br>canvas_oop_rasterization: disabled_off<br>direct_rendering_display_compositor: disabled_off_ok<br>gpu_compositing: enabled<br>multiple_raster_threads: enabled_on<br>opengl: enabled_on<br>rasterization: enabled<br>raw_draw: disabled_off_ok<br>skia_renderer: enabled_on<br>video_decode: enabled<br>video_encode: enabled<br>vulkan: disabled_off<br>webgl: enabled<br>webgl2: enabled<br>webgpu: disabled_off|
|Load (avg)|undefined|
|Memory (System)|15.81GB (5.85GB free)|
|Process Argv||
|Screen Reader|no|
|VM|0%|
</details>

**Comment by sirmspencer** [comment]
Hmm.  I think there might be something here. I'll look when I get a chance.

**Comment by dmo-odoo** [comment]
I was just hit by the same issue. I uninstalled the extension in search for something else that works but it turns out there isn't anything else that would hide the Panel (Terminal, Debug, etc) on start. Therefore I reinstalled the extension in hopes of quickly finding the bug and fixing it locally, which I did. Then I realized the error was already fixed in the code of your repository with https://github.com/sirmspencer/vscode-autohide/pull/35. However, the extension is not up to date on the vscode marketplace. When installing the extension from there, you get the outdated code with the bug.

**Comment by sirmspencer** [comment]
I accidentally published it with the same version.  It should be updated now.  Holy eff microsoft is annoying to work with if you cant remember your organizations.  wtf is there no landing page for that.

**Comment by mrx23dot** [comment]
v1.0.9 still hides sidebar when opening a folder.

**Comment by sirmspencer** [comment]
I think I miss deployed 1.0.9.  Try 1.0.10.  Make sure to look at setting `autoHide.hideOnOpen` to false.

**Comment by mrx23dot** [comment]
1.0.10 works great, thank you!
